PeerOrgs:
  - Name: Org1
    Domain: org1.example.com
    EnableNodeOUs: true
    Template:
      SANS:
        - "localhost"
        - "127.0.0.1"
    Specs:
      - Hostname: orderer0
        SANS:
          - "localhost"
          - "127.0.0.1"
      - Hostname: peer0
      - Hostname: peer1
    Users:
      Count: 0
    
  - Name: Org2
    Domain: org2.example.com
    EnableNodeOUs: true
    Template:
      SANS:
        - "localhost"
        - "127.0.0.1"
    Specs:
      - Hostname: orderer0
        SANS:
          - "localhost"
          - "127.0.0.1"
      - Hostname: peer0
      - Hostname: peer1
    Users:
      Count: 0
    
  - Name: Org3
    Domain: org3.example.com
    EnableNodeOUs: true
    Template:
      SANS:
        - "localhost"
        - "127.0.0.1"
    Specs:
      - Hostname: orderer0
        SANS:
          - "localhost"
          - "127.0.0.1"
      - Hostname: peer0
      - Hostname: peer1
    Users:
      Count: 0

  - Name: Org4
    Domain: org4.example.com
    EnableNodeOUs: true
    Template:
      SANS:
        - "localhost"
        - "127.0.0.1"
    Specs:
      - Hostname: orderer0
        SANS:
          - "localhost"
          - "127.0.0.1"
      - Hostname: peer0
      - Hostname: peer1
    Users:
      Count: 0

  - Name: Org5
    Domain: org5.example.com
    EnableNodeOUs: true
    Template:
      SANS:
        - "localhost"
        - "127.0.0.1"
    Specs:
      - Hostname: orderer0
        SANS:
          - "localhost"
          - "127.0.0.1"
      - Hostname: peer0
      - Hostname: peer1
    Users:
      Count: 0



      