global:
  scrape_interval: 15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.
alerting:
  alertmanagers:
    - static_configs:
        - targets:
rule_files:
scrape_configs:
  - job_name: "prometheus"
    scrape_interval: 10s
    static_configs:
      - targets: ["51.38.54.24:9090"]
  - job_name: "Peers.org4"
    static_configs:
      - targets: ["51.38.54.24:9440","51.38.54.24:9441"]
  - job_name: "Orderers.org4"
    static_configs:
      - targets: ["51.38.54.24:9445"]